rental_site/main/urls.py
from . import views
from django.urls import path
from django.urls import include
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from .models import Ad

ads_dict = {
    'queryset': Ad.objects.all(),
    'date_field': 'date_added',
}


urlpatterns = [
    path('', views.Index.as_view()),
    path('sell/apartment/', views.ApartmentSell.as_view(), name='apartment_sell'),
    path('sell/room/', views.RoomSell.as_view(), name='room_sell'),
    path('sell/garage/', views.GarageSell.as_view(), name='garage_sell'),
    path('sell/land_plot/', views.LandPlotSell.as_view(), name='land_plot_sell'),
    path('rent/apartment/', views.ApartmentRent.as_view(), name='apartment_rent'),
    path('rent/room/', views.RoomRent.as_view(), name='room_rent'),
    path('rent/garage/', views.GarageRent.as_view(), name='garage_rent'),
    path('ad/<str:slug>/', views.AdDetail.as_view(), name='ad_detail'),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('dashboard/add/', views.RealtyList.as_view(), name='choice_type'),
    path('accounts/profile/', views.UserUpdate.as_view(), name='edit_user_profile'),
    path('ad/add/apartment/', views.AddApartment.as_view(), name='add_apartment'),
    path('ad/add/room/', views.AddRoom.as_view(), name='add_room'),
    path('ad/add/garage/', views.AddGarage.as_view(), name='add_garage'),
    path('ad/add/land-plot/', views.AddLandPlot.as_view(), name='add_land_plot'),
    path('ad/add/photos/<uuid:pk>/', views.SaveImages.as_view(), name='add_image'),
    path('ad/edit/<uuid:pk>/', views.EditRealtyAd.as_view(), name='edit_ad'),
    path('search/', views.SearchAd.as_view(), name='search_ad'),
    path('sitemap.xml', sitemap, {'sitemaps': {'rental_site': GenericSitemap(ads_dict, priority=0.6)}},
         name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt", views.robots_txt)
]

rental_site/rental_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    path('sentry-debug/', trigger_error),
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rental_site/main/models.py
import uuid
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from pytils.translit import slugify
from django.contrib.sites.models import Site

# Create your models here.


class Profile(models.Model):
    """Профайл пользователя."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=12, blank=True)
    age = models.PositiveSmallIntegerField(blank=True, null=True)

    def __str__(self) -> str:
        return 'Profile for user {}'.format(self.user)


class Region(models.Model):
    """Регион."""

    name = models.CharField(max_length=200, verbose_name='Название', unique=True, db_index=True)
    slug = models.SlugField(primary_key=True, blank=True)

    def __str__(self) -> str:
        return str(self.name)

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Населенный пункт'
        verbose_name_plural = 'Населенные пункты'


class Ad(models.Model):
    """Объявление недвижимости."""

    uniq_id = models.UUIDField(primary_key=True, default=uuid.uuid1, editable=False)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cost = models.PositiveIntegerField()
    description = models.CharField(max_length=255)
    address = models.CharField(max_length=200)
    slug = models.SlugField(blank=True)
    date_added = models.DateField(auto_now_add=True)
    view_count = models.PositiveIntegerField(default=0)
    STATUS_CHOICES = [
        ('published', 'Опубликовано'),
        ('not_active', 'Модерируется'),
        ('archive', 'Архив'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='not_active')
    ACTION_CHOICES = [
        ('sell', 'Продажа'),
        ('rent', 'Аренда'),
    ]
    action = models.CharField(max_length=20, choices=ACTION_CHOICES)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, limit_choices_to={
        'model__in': (
            'apartment',
            'room',
            'garage',
            'landplot'
        )
    })
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey(ct_field='content_type', fk_field='object_id')
    custom_tags = ArrayField(models.CharField(max_length=50, blank=True))

    def save(self, *args, **kwargs) -> None:
        self.slug = f"{slugify(self.description)[:30].replace(' ', '-')}-{str(self.uniq_id)}"
        super().save(*args, **kwargs)

    def get_absolute_url(self) -> str:
        return reverse('ad_detail', kwargs={'slug': self.slug})

    def get_full_absolute_url(self) -> str:
        """Ссылка на объявлении с доменом в адрессе."""

        domain = Site.objects.get_current().domain
        return f'http://{domain}{self.get_absolute_url()}'

    def __str__(self) -> str:
        return self.description[:40]

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['date_added']


class Image(models.Model):
    """Фото объекта недвижимости."""

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE, default=True)
    image = models.ImageField(upload_to='image_folder', verbose_name='Изображение')


class UserAd(models.Model):
    """
    PostgreSQL View
    SQL:
        CREATE OR REPLACE VIEW user_ad AS
            SELECT ad.description as ad_description, ad.region_id as ad_region, ad.cost as ad_cost, ad.user_id as user_id
            FROM django_db.public.main_ad as ad
            INNER JOIN django_db.public.auth_user AS u on u.id = user_id
    """

    user_id = models.IntegerField()
    ad_description = models.CharField(max_length=255)
    ad_region = models.CharField(max_length=200)
    ad_cost = models.PositiveIntegerField()

    class Meta:
        managed = False
        db_table = "user_ad"

    def __str__(self):
        return self.ad_description


class Realty(models.Model):
    """Базовый класс модели недвижимость."""

    total_square = models.FloatField(default=True)

    class Meta:
        abstract = True


class Apartment(Realty):
    """Квартира."""

    BUILDING_CHOICES = ([
        ('new', 'Новостройка'),
        ('second', 'Вторичка')
    ])
    floor = models.PositiveSmallIntegerField()
    number_of_rooms = models.PositiveSmallIntegerField()
    kitchen_square = models.FloatField()
    living_square = models.FloatField()
    building = models.CharField(max_length=20, choices=BUILDING_CHOICES)

    class Meta:
        verbose_name = 'Квартира'
        verbose_name_plural = 'Квартиры'

    def __str__(self) -> str:
        return 'Квартира'


class Room(Realty):
    """Комната."""

    floor = models.PositiveSmallIntegerField()

    class Meta:
        verbose_name = 'Комната'
        verbose_name_plural = 'Комнаты'

    def __str__(self) -> str:
        return 'Комната'


class Garage(Realty):
    """Гараж."""

    number_of_floors = models.PositiveSmallIntegerField()

    class Meta:
        verbose_name = 'Гараж'
        verbose_name_plural = 'Гаражы'

    def __str__(self) -> str:
        return 'Гараж'


class LandPlot(Realty):
    """Земельный участок."""

    class Meta:
        verbose_name = 'Земельный участок'
        verbose_name_plural = 'Земельные участки'

    def __str__(self) -> str:
        return 'Земля'


class Tag(models.Model):
    """Тэги сайта."""

    name = models.CharField(max_length=50)
    slug = models.SlugField(blank=True)
    ads = models.ManyToManyField(Ad)

    def save(self, *args, **kwargs) -> None:
        self.slug = f"{slugify(self.name).replace(' ', '-')}"
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'


class Subscribers(models.Model):
    """Подписчики на рассылку объявлений."""

    email = models.EmailField(unique=True)

rental_site/main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Ad, Apartment, Room, Garage, LandPlot, Profile, Subscribers, Region
from django.core.exceptions import ValidationError


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('age', 'phone_number',)

    def clean_age(self):
        current_age = self.cleaned_data['age']
        if int(current_age) < 18:
            raise ValidationError('Вы слишком молоды')

        return current_age


class AdForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = ('region', 'description', 'cost', 'address', 'action', 'custom_tags', )


class ApartmentForm(forms.ModelForm):
    class Meta:
        model = Apartment
        fields = '__all__'


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = '__all__'


class LandPlotForm(forms.ModelForm):
    class Meta:
        model = LandPlot
        fields = '__all__'


class GarageForm(forms.ModelForm):
    class Meta:
        model = Garage
        fields = '__all__'


class SubscribersForm(forms.ModelForm):
    class Meta:
        model = Subscribers
        fields = '__all__'


class SearchApartmentForm(forms.Form):
    ROOM_CHOICES = ([
        ('', '-'),
        ('1', '1-комнатные'),
        ('2', '2-комнатные'),
        ('3', '3-комнатные'),
        ('4', '4-комнатные и более')
    ])
    BUILDING_CHOICES = ([
        ('', '-'),
        ('new', 'Новостройка'),
        ('second', 'Вторичка')
    ])
    PRICE_RANGE = ([
        ('', '-'),
        ('1000000', 'до 1млн рублей'),
        ('2000000', 'от 1 до 2млн рублей'),
        ('3000000', 'От 2 до 3млн рублей'),
        ('5000000', 'От 3 до 5 млн рублей'),
        ('max', 'Более 5 млн рублей')
    ])

    room_count = forms.ChoiceField(required=True, choices=ROOM_CHOICES, label='Количество комнат')
    action = forms.ChoiceField(required=True, choices=BUILDING_CHOICES, label='Тип жилья')
    price = forms.ChoiceField(required=True, choices=PRICE_RANGE, label='Стоимость')
    region = forms.ModelChoiceField(required=True, queryset=Region.objects.all(), label='Населенный пункт')

    room_count.widget.attrs.update({'class': 'form-control', 'id': 'ptypes'})
    action.widget.attrs.update({'class': 'form-control', 'id': 'lookingfor'})
    price.widget.attrs.update({'class': 'form-control', 'id': 'price'})
    region.widget.attrs.update({'class': 'form-control', 'id': 'location'})


class SearchForm(forms.Form):
    search = forms.CharField(required=True)
    search.widget.attrs.update({'class': 'form-control', 'id': 'search'})

rental_site/main/templates/choice_type.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}
{% block dashboard_content %}
    <!-- Basic Information -->
    <h4>Выберите тип объявления</h4>
    <div class="custom-tab style-1">
        <ul class="nav nav-tabs pb-2 b-0" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'add_apartment' %}" role="tab" aria-controls="home" aria-selected="true">Квартиру</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'add_room' %}" role="tab" aria-controls="profile" aria-selected="false">Комнату</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'add_garage' %}" role="tab" aria-controls="contact" aria-selected="false">Гараж</a>
            </li>
            <li class="nav-item">
                <a class="nav-link"  href="{% url 'add_land_plot' %}" role="tab" aria-controls="contact" aria-selected="false">Земельный участок</a>
            </li>
        </ul>
    </div>
{% endblock %}

rental_site/main/templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
{% include 'components/header.html' %}
<section class="gray p-0">
				<div class="container-fluid p-0">
					<div class="row">
						<div class="col-lg-3 col-md-4 col-sm-12">
							<div class="property_dashboard_navbar">
								<div class="dash_user_menues">
									<ul>
										<li><a href="{% url 'dashboard' %}"><i class="ti-dashboard"></i>Личный кабинет</a></li>
										<li><a href="{% url 'edit_user_profile' %}"><i class="ti-user"></i>Редактировать профиль</a></li>
										<li><a href="#"><i class="ti-layers"></i>Мои Объявления</a></li>
										<li><a href="{% url 'choice_type' %}"><i class="ti-layers"></i>Добавить Объявления</a></li>
										<li><a href="#"><i class="ti-unlock"></i>Сменить пароль</a></li>
										<li><a href="{% url 'account_logout' %}"><i class="ti-power-off"></i>Выйти</a></li>
									</ul>
								</div>
							</div>
						</div>
						<div class="col-lg-9 col-md-8 col-sm-12">
							<div class="dashboard-body">
								<div class="dashboard-wraper">
                                    {% block dashboard_content %}
                                    {% endblock %}
								</div>
								<div class="row">
									<div class="col-md-12 col-lg-12 mt-4">
										<footer class="text-center">
											<p class="mb-0">© {% now 'Y' %} Develop By <a href="#">Stepanov Vladimir</a> All Rights Reserved</p>
										</footer>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
{% endblock %}

rental_site/main/templates/form.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}
{% block dashboard_content %}
    <!-- Basic Information -->
    <div class="frm_submit_block">
        <h4>{{ title }}</h4>
        <div class="frm_submit_wrap">
            {% if messages %}
              {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}" role="alert">
                      {{ message }}
                  </div>
              {% endfor %}
            {% endif %}
            <div class="form-row">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy  }}
                    {{ additional_form|crispy }}
                    <div class="form-group col-lg-12 col-md-12 mt-3">
                        <button class="btn btn-theme bg-2" type="submit">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

rental_site/main/templates/form_files.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}
{% block dashboard_content %}
    <!-- Basic Information -->
    <div class="frm_submit_block">
        <h4>{{ title }}</h4>
        <div class="frm_submit_wrap">
            {% if messages %}
              {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}" role="alert">
                      {{ message }}
                  </div>
              {% endfor %}
            {% endif %}
            <div class="form-row">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy  }}
                    {{ additional_form|crispy }}
                    <div class="form-group col-lg-12 col-md-12 mt-3">
                        <button class="btn btn-theme bg-2" type="submit">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

rental_site/main/templates/index.html
{% extends 'base.html' %}
{% block json_ld %}
<script type='application/ld+json'>
    {
      "@context": "http://www.schema.org",
      "@type": "WebSite",
      "name": "Продажа недвижимости хакасии",
      "alternateName": "Продажа и аренда недвижимости в республики хакасия",
      "url": "http://0.0.0.0:8000/"
    }
 </script>
{% endblock %}
{% load custom_tags %}
{% block content %}
{% load crispy_forms_tags %}
{% include 'components/header.html' %}
<div class="image-cover hero_banner"
     style="background:#334aca url('https://cs8.pikabu.ru/post_img/big/2017/08/11/4/1502425645172160116.jpg') no-repeat;"
     data-overlay="1">
    <div class="container">

        <h1 class="big-header-capt mb-0">Продажа недвижимости Хакасии</h1>
        <p class="text-center mb-5">Квартиры, Комнаты, Недвижимость - Абакан, Саяногорск, Сорск, Черногорск, Абаза</p>
        <!-- Type -->
        <div class="full_search_box nexio_search lightanic_search hero_search-radius modern">
            <div>
                    <form method="get" action="{% url 'search_ad' %}" class="row">
                        {{ search_form.as_p }}
                        <button type="submit" class="btn">Search</button>
                    </form>
            </div>
        </div>
    </div>
</div>
<!-- ============================ Hero Banner End ================================== -->

{% for ads in best_deal_ads %}
    {% for ad in ads %}
    {% endfor %}
{% endfor %}


{% include 'components/subscribe/subscribe.html' %}
{% include 'components/footer.html' %}
{% endblock %}

rental_site/main/templates/item_ad.html
{% extends 'base.html' %}
{% block meta %}
    <title>{{ ad.description }}</title>
    <meta name="description" content="{{ ad.description }}" />
{% endblock %}
{% block content %}
{% include 'components/header.html' %}
<section class="gray-dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-12 col-sm-12">
                <!-- Single Block Wrap -->
                 <div class="property_block_wrap style-2 mb-3">

                    <div class="property_block_wrap_header">
                        <a data-toggle="collapse" data-parent="#dsrp" href="#clTwo" aria-expanded="true"><h4 class="property_block_title">Фото</h4></a>
                    </div>
                    <div id="clOne" class="panel-collapse collapse show" aria-expanded="true">
                       <div class="block-body">
                     <div class="carousel-inner">
                          {% for img in ad.image_set.all %}
                              {% if forloop.first %}
                                <div class="carousel-item active">
                                      <img class="d-block w-100 img-responsive" src="{{ img.image.url }}" alt="First slide">
                                </div>
                              {% else %}
                                <div class="carousel-item">
                                  <img class="d-block w-100 img-responsive" src="{{ img.image.url }}" alt="First slide">
                                </div>
                              {% endif %}
                          {% endfor %}
                          </div>
                          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                        </div>

                        </div>
                    </div>

                </div>
                <div class="property_block_wrap style-2">
                    <div class="property_block_wrap_header">
                        <a data-toggle="collapse" data-parent="#features" href="#clOne" aria-expanded="true"><h4 class="property_block_title">&#x20bd;{{ ad.cost }}</h4></a>
                    </div>
                    <div id="clTwo" class="panel-collapse collapse show" aria-expanded="true">
                        <div class="block-body">
                            <ul class="deatil_features">
                                <li><strong>Общая площадь:</strong>{{ ad.content_object.floor }}</li>
                                <li><strong>Жилая:</strong>{{ ad.content_object.living_square }}</li>
                                <li><strong>Кухня:</strong>{{ ad.content_object.kitchen_square }}</li>
                                <li><strong>Этаж:</strong>{{ ad.content_object.floor }}</li>
                                <li><strong>Комнат:</strong>{{ ad.content_object.number_of_rooms }}</li>
                                <li><strong>Адрес:</strong>{{ ad.address }}</li>
                                <li><strong>Город:</strong>{{ ad.region }}</li>
                                <li><strong>Дата размещения:</strong>{{ ad.date_added }}</li>
                                <li><strong>Просмотры</strong>{{ counter }}-{{ ad.view_count }}</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- Single Block Wrap -->
                <div class="property_block_wrap style-2">

                    <div class="property_block_wrap_header">
                        <a data-toggle="collapse" data-parent="#dsrp" href="#clTwo" aria-expanded="true"><h4 class="property_block_title">Описание</h4></a>
                    </div>
                    <div id="clThree" class="panel-collapse collapse show" aria-expanded="true">
                        <div class="block-body">
                        <p>
                            {{ ad.description }}
                        </p>
                        </div>
                    </div>
                </div>

            </div>
            <!-- property Sidebar -->
            <div class="col-lg-4 col-md-12 col-sm-12">
                <div class="property-sidebar">
                </div>
            </div>
        </div>
    </div>
</section>
{% include 'components/footer.html' %}
{% endblock %}

rental_site/main/templates/list_ad.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block meta %}
    <title>{{ action }} {{ realty }} в республике Хакасия</title>
    <meta name="description" content="{{ action }} {{ realty }}. Объявления в республике Хакасия." />
{% endblock %}
{% block content %}
{% include 'components/header.html' %}
<div class="filterspaces">
    <div class="container">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-9 col-md-9 col-sm-8 col-9">
                    <div class="filterspace__controls">
                        <ul class="nav nav-pills" id="pills-tab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="rent-tab" data-toggle="pill" href="#pills-rent"
                                   role="tab" aria-controls="pills-rent" aria-selected="true">Rent</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="buy-tab" data-toggle="pill" href="#pills-buy" role="tab"
                                   aria-controls="pills-buy" aria-selected="false">Buy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="sell-tab" data-toggle="pill" href="#pills-sell" role="tab"
                                   aria-controls="pills-sell" aria-selected="false">Sell</a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-3 col-md-3 col-sm-4 col-3">
                    <div class="filterspace__link">
                        <a href="javascript_voide(0);" class="filt_link" data-toggle="modal"
                           data-target="#searchfilter"><i class="ti-filter mr-1"></i><span>Filters</span></a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<section>
    <div class="container">
        <div class="row">
        <div class="single_widgets widget_tags" style="padding:0;border:0;">
            <ul>
                {% for tag in tags %}
                    <li><a href="?tag={{ tag.slug }}" target="_blank">{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        </div>
        <div class="row">
            <!-- Single Property -->
            {% for ad in ads %}
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="list-slide-box">
                        <div class="modern-list border border-secondary">
                            <div class="grid-category-thumb">
                                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                                  <div class="carousel-inner">
                                  {% for img in ad.image_set.all %}
                                      {% if forloop.first %}
                                        <div class="carousel-item active">
                                              <img class="d-block w-100 img-responsive" src="{{ img.image.url }}" alt="First slide">
                                        </div>
                                      {% else %}
                                        <div class="carousel-item">
                                          <img class="d-block w-100 img-responsive" src="{{ img.image.url }}" alt="First slide">
                                        </div>
                                      {% endif %}
                                  {% endfor %}
                                  </div>
                                  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                  </a>
                                  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Next</span>
                                  </a>
                                </div>
                            </div>
                            <div class="modern-list-content">
                                <div class="listing-content-wrap smalls">
                                    <h4 class="lst-title text-lowercase">
                                        <a href="{{ ad.get_absolute_url }}" target="_blank">
                                            {% ads_title ad %}
                                            {{ad.content_object.total_square}}м<sup>2</sup>
                                        </a>
                                    </h4>
                                    <p>{{ ad.address }}, {{ ad.region }}</p>
                                    <p>
                                        {% for custom_tag in ad.custom_tags %}
                                            <a href="?custom_tag={{ custom_tag }}">{{ custom_tag }}</a>
                                        {% endfor %}
                                    </p>
                                </div>
                                <div class="listing-footer-wrap property-lists mt-2">
                                    <div class="property-lists flex-1">
                                        <ul>
                                            {% ads_options ad %}
                                        </ul>
                                    </div>
                                    <h4 class="mdr-price">&#x20bd; {{ ad.cost }}</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
        <!-- Pagination -->
        {% if is_paginated %}
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <ul class="pagination p-center">
                        {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                                    <li class="page-item active"><a href="#" class="page-link">{{ i }}</a></li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' i %}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
    </div>
</section>
{% include 'components/footer.html' %}
{% endblock %}

rental_site/main/templates/mobile_index.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block content %}
{% load crispy_forms_tags %}
{% include 'components/header.html' %}
<div class="image-cover hero_banner" style="background:#334aca url('https://cs8.pikabu.ru/post_img/big/2017/08/11/4/1502425645172160116.jpg') no-repeat;" data-overlay="1">
    <div class="container">

        <h1 class="big-header-capt mb-0">Продажа недвижимости Хакасии</h1>
        <p class="text-center mb-5">Квартиры, Комнаты, Недвижимость - Абакан, Саяногорск, Сорск, Черногорск, Абаза</p>
        <!-- Type -->
        <div class="full_search_box nexio_search lightanic_search hero_search-radius modern">
            <div>
                    <form method="get" action="{% url 'search_ad' %}" class="row">
                        {{ search_form.as_p }}
                        <button type="submit" class="btn">Search</button>
                    </form>
            </div>
        </div>
    </div>
</div>
<!-- ============================ Hero Banner End ================================== -->

{% for ads in best_deal_ads %}
    {% for ad in ads %}
    {% endfor %}
{% endfor %}


{% include 'components/subscribe/subscribe.html' %}
{% include 'components/footer.html' %}
{% endblock %}